apiVersion: apps/v1
kind: Deployment
metadata:
  name: gwconsumer-deployment
  labels:
    app: gwconsumer
spec:
  replicas: 10
  selector:
    matchLabels:
      app: gwconsumer
  template:
    metadata:
      labels:
        app: gwconsumer
    spec:
      containers:
      - name: gwconsumer
        image: fracasula/gwconsumer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PULSAR_URL
          value: "pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"
        - name: TOPIC_NAME
          value: "persistent://public/fcasula/gwpulsar-test"
        - name: BATCH_MAX_DELAY
          value: "10ms"
        - name: BATCH_MAX_MESSAGES
          value: "1000"
        - name: MAX_CONNECTIONS_PER_BROKER
          value: "20"
      imagePullSecrets:
      - name: regcred
