apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gwserver-statefulset
  labels:
    app: gwserver
spec:
  serviceName: "gwserver-svc"
  replicas: 10
  selector:
    matchLabels:
      app: gwserver
  template:
    metadata:
      labels:
        app: gwserver
    spec:
      containers:
      - name: gwserver
        image: fracasula/gwserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PULSAR_URL
          value: "pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"
        - name: TOPIC_NAME
          value: "persistent://public/fcasula/gwpulsar-test"
        - name: CUSTOM_MESSAGE_ROUTER
          value: "true"
        - name: BATCH_MAX_DELAY
          value: "10ms"
        - name: BATCH_MAX_MESSAGES
          value: "1000"
        - name: MAX_CONNECTIONS_PER_BROKER
          value: "10"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gwserver-svc
  labels:
    app: gwserver
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: gwserver
